# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_validation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
